# Generated by Django 3.2.4 on 2021-06-23 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='наименование')),
                ('short_name', models.CharField(max_length=128, verbose_name='короткое наименование')),
                ('description', models.TextField(verbose_name='описание')),
                ('version', models.CharField(max_length=64, unique=True, verbose_name='версия')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='дата начала действия справочника этой версии')),
            ],
            options={
                'verbose_name': 'справочник',
                'verbose_name_plural': 'справочники',
            },
        ),
        migrations.CreateModel(
            name='GuideElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_code', models.CharField(max_length=64, verbose_name='код элемента')),
                ('element_value', models.CharField(max_length=255, verbose_name='значение элемента')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_elements', to='guide.guide', verbose_name='родительский идентификатор')),
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'элементы',
            },
        ),
    ]
