# Generated by Django 3.2.4 on 2021-06-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20210624_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(max_length=255, verbose_name='наименование'),
        ),
    ]
