# Generated by Django 3.2.4 on 2021-07-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_alter_guide_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='short_name',
            field=models.CharField(max_length=64, verbose_name='короткое наименование'),
        ),
        migrations.AlterUniqueTogether(
            name='guideelement',
            unique_together={('element_code', 'guide')},
        ),
    ]
