# Generated by Django 3.2.4 on 2021-07-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_auto_20210703_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='version',
            field=models.CharField(max_length=64, verbose_name='версия'),
        ),
        migrations.AlterUniqueTogether(
            name='guide',
            unique_together={('name', 'version')},
        ),
    ]
